import fs from 'node:fs';
import path from 'node:path';
import { loadDecisions, applySupersedes, summarize } from './decisions.js';
import { firstSentence } from './util.js';

export const START = '<!-- porque:start -->';
export const END = '<!-- porque:end -->';

const noComments = (t = '') => String(t).replace(/<!--/g, '<!‑‑').replace(/-->/g, '‑‑>');

export function renderContextBlock(cfg, decisions) {
  const active = decisions.filter((d) => d.status === 'active').slice(0, cfg.maxContextDecisions);
  const es = cfg.lang === 'es';
  const lines = [START,
    `## ${cfg.h.context}`, '',
    es ? `Estas decisiones ya fueron tomadas por el equipo. Respetalas. Si una tarea te obliga a contradecir alguna, decilo explícitamente antes de hacerlo y explicá por qué. Antes de modificar un archivo o elegir una librería, patrón o formato, consultá la tool \`porque_why\` con el path o el tema. Si tomás con el usuario una decisión que un compañero podría deshacer sin saberlo, registrala con \`porque_record\`. El detalle completo está en \`${cfg.decisionsDir}/\`.`
       : `The team already made these decisions. Respect them. If a task forces you to contradict one, say so explicitly before doing it and explain why. Before modifying a file or choosing a library, pattern or format, call the \`porque_why\` tool with the path or topic. If you and the user make a decision a teammate could undo without knowing, record it with \`porque_record\`. Full detail lives in \`${cfg.decisionsDir}/\`.`,
    ''];
  if (!active.length) lines.push(es ? '_Todavía no hay decisiones registradas._' : '_No decisions recorded yet._');
  for (const d of active) {
    const scope = d.scope.length ? ` \`${d.scope.slice(0, 3).join('`, `')}\`` : '';
    lines.push(noComments(`- **${d.title}** (${d.date})${scope}: ${summarize(d)} ${es ? 'Por qué' : 'Why'}: ${firstSentence(d.why)} → \`${d.rel}\``));
  }
  lines.push('', `_${es ? 'Generado por' : 'Generated by'} Porque · ${active.length} ${es ? 'decisiones activas' : 'active decisions'}_`, END);
  return lines.join('\n');
}

export function renderIndex(cfg, decisions) {
  const es = cfg.lang === 'es';
  const rows = decisions.map((d) => `| ${d.date} | [${d.title}](./${path.basename(d.file)}) | ${d.status} | ${d.scope.slice(0, 2).join(', ') || '-'} | ${d.tags.join(', ') || '-'} |`);
  return [`# ${cfg.h.index}`, '',
    es ? 'Cada archivo es una decisión con su razonamiento, capturada de sesiones de trabajo con IA por [Porque](https://github.com/MiguelOvejeroD/porque). Editá a mano lo que quieras: el archivo es la fuente de verdad.'
       : 'Each file is one decision with its reasoning, captured from AI coding sessions by [Porque](https://github.com/MiguelOvejeroD/porque). Edit freely: the file is the source of truth.',
    '',
    es ? '| Fecha | Decisión | Estado | Alcance | Tags |' : '| Date | Decision | Status | Scope | Tags |',
    '|---|---|---|---|---|', ...rows, ''].join('\n');
}

export function sync(cfg, { quiet } = {}) {
  const decisions = applySupersedes(loadDecisions(cfg));
  const block = renderContextBlock(cfg, decisions);
  const files = [];
  for (const rel of cfg.contextFiles) {
    const file = path.join(cfg.root, rel);
    let content = fs.existsSync(file) ? fs.readFileSync(file, 'utf8') : `# ${path.basename(cfg.root)}\n\n`;
    const s = content.indexOf(START), e = content.lastIndexOf(END);
    if (s !== -1 && e !== -1) content = content.slice(0, s) + block + content.slice(e + END.length);
    else content = content.replace(/\s*$/, '') + '\n\n' + block + '\n';
    fs.writeFileSync(file, content);
    files.push(rel);
  }
  fs.mkdirSync(cfg.decisionsPath, { recursive: true });
  fs.writeFileSync(path.join(cfg.decisionsPath, 'README.md'), renderIndex(cfg, decisions));
  if (!quiet) process.stderr.write(`porque: ${decisions.filter((d) => d.status === 'active').length} active decision(s) synced into ${files.join(', ')} and ${cfg.decisionsDir}/README.md\n`);
  return { files, count: decisions.length };
}
